% =========================================================================
% REHAZENTER TOOLBOX
% =========================================================================
% File name:    plotCycle
% -------------------------------------------------------------------------
% Subject:      Plot markers during gait cycle
% -------------------------------------------------------------------------
% Inputs:       - Markers (structure)
%               - Vmarkers (structure)
%               - n (int)
%               - side (char)
%               - system (char)
% Outputs:      
% -------------------------------------------------------------------------
% Author: F. Moissenet, C. Schreiber, A. Naaim
% Date of creation: 26/03/2014
% Version: 1
% -------------------------------------------------------------------------
% Updates:
% =========================================================================

function plotCycle(Markers,Vmarkers,n,side,system)

for i = 1:n
    
    fig = figure(2); hold on; axis equal; view(45,20);
    
    if strcmp(system,'BTS')

        plot3(permute(Markers.sacrum(1,1,i),[3,1,2]),permute(-Markers.sacrum(3,1,i),[3,1,2]),permute(Markers.sacrum(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Red','Markersize',20);
        plot3(permute(Markers.r_asis(1,1,i),[3,1,2]),permute(-Markers.r_asis(3,1,i),[3,1,2]),permute(Markers.r_asis(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Red','Markersize',20);
        plot3(permute(Markers.l_asis(1,1,i),[3,1,2]),permute(-Markers.l_asis(3,1,i),[3,1,2]),permute(Markers.l_asis(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Red','Markersize',20);
        plot3(permute(Markers.r_thigh(1,1,i),[3,1,2]),permute(-Markers.r_thigh(3,1,i),[3,1,2]),permute(Markers.r_thigh(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Red','Markersize',20);
        plot3(permute(Markers.r_bar_1(1,1,i),[3,1,2]),permute(-Markers.r_bar_1(3,1,i),[3,1,2]),permute(Markers.r_bar_1(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Red','Markersize',20);
        plot3(permute(Markers.r_knee_1(1,1,i),[3,1,2]),permute(-Markers.r_knee_1(3,1,i),[3,1,2]),permute(Markers.r_knee_1(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Red','Markersize',20);
        plot3(permute(Markers.r_knee_2(1,1,i),[3,1,2]),permute(-Markers.r_knee_2(3,1,i),[3,1,2]),permute(Markers.r_knee_2(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Red','Markersize',20);
        plot3(permute(Markers.r_bar_2(1,1,i),[3,1,2]),permute(-Markers.r_bar_2(3,1,i),[3,1,2]),permute(Markers.r_bar_2(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Red','Markersize',20);
        plot3(permute(Markers.r_mall(1,1,i),[3,1,2]),permute(-Markers.r_mall(3,1,i),[3,1,2]),permute(Markers.r_mall(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Red','Markersize',20);
        if isfield(Markers,'Markers.r_heel')
            plot3(permute(Markers.r_heel(1,1,i),[3,1,2]),permute(-Markers.r_heel(3,1,i),[3,1,2]),permute(Markers.r_heel(2,1,i),[3,1,2]), ...
                'Marker','.','Color','Green','Markersize',20);
        end
        plot3(permute(Markers.r_met(1,1,i),[3,1,2]),permute(-Markers.r_met(3,1,i),[3,1,2]),permute(Markers.r_met(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Red','Markersize',20);
        plot3(permute(Markers.l_asis(1,1,i),[3,1,2]),permute(-Markers.l_asis(3,1,i),[3,1,2]),permute(Markers.l_asis(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Red','Markersize',20);
        plot3(permute(Markers.l_asis(1,1,i),[3,1,2]),permute(-Markers.l_asis(3,1,i),[3,1,2]),permute(Markers.l_asis(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Red','Markersize',20);
        plot3(permute(Markers.l_thigh(1,1,i),[3,1,2]),permute(-Markers.l_thigh(3,1,i),[3,1,2]),permute(Markers.l_thigh(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Red','Markersize',20);
        plot3(permute(Markers.l_bar_1(1,1,i),[3,1,2]),permute(-Markers.l_bar_1(3,1,i),[3,1,2]),permute(Markers.l_bar_1(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Red','Markersize',20);
        plot3(permute(Markers.l_knee_1(1,1,i),[3,1,2]),permute(-Markers.l_knee_1(3,1,i),[3,1,2]),permute(Markers.l_knee_1(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Red','Markersize',20);
        plot3(permute(Markers.l_knee_2(1,1,i),[3,1,2]),permute(-Markers.l_knee_2(3,1,i),[3,1,2]),permute(Markers.l_knee_2(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Red','Markersize',20);
        plot3(permute(Markers.l_bar_2(1,1,i),[3,1,2]),permute(-Markers.l_bar_2(3,1,i),[3,1,2]),permute(Markers.l_bar_2(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Red','Markersize',20);
        plot3(permute(Markers.l_mall(1,1,i),[3,1,2]),permute(-Markers.l_mall(3,1,i),[3,1,2]),permute(Markers.l_mall(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Red','Markersize',20);
        if isfield(Markers,'Markers.l_heel')
            plot3(permute(Markers.l_heel(1,1,i),[3,1,2]),permute(-Markers.l_heel(3,1,i),[3,1,2]),permute(Markers.l_heel(2,1,i),[3,1,2]), ...
                'Marker','.','Color','Green','Markersize',20);
        end
        plot3(permute(Markers.l_met(1,1,i),[3,1,2]),permute(-Markers.l_met(3,1,i),[3,1,2]),permute(Markers.l_met(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Red','Markersize',20);

        plot3(permute(Vmarkers.ljc(1,1,i),[3,1,2]),permute(-Vmarkers.ljc(3,1,i),[3,1,2]),permute(Vmarkers.ljc(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Blue','Markersize',20);
        plot3(permute(Vmarkers.r_hjc(1,1,i),[3,1,2]),permute(-Vmarkers.r_hjc(3,1,i),[3,1,2]),permute(Vmarkers.r_hjc(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Blue','Markersize',20);
        plot3(permute(Vmarkers.l_hjc(1,1,i),[3,1,2]),permute(-Vmarkers.l_hjc(3,1,i),[3,1,2]),permute(Vmarkers.l_hjc(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Blue','Markersize',20);
        if isfield(Vmarkers,'r_kjc')
            plot3(permute(Vmarkers.r_kjc(1,1,i),[3,1,2]),permute(-Vmarkers.r_kjc(3,1,i),[3,1,2]),permute(Vmarkers.r_kjc(2,1,i),[3,1,2]), ...
                'Marker','.','Color','Blue','Markersize',20);
        end
        if isfield(Vmarkers,'r_ajc')
            plot3(permute(Vmarkers.r_ajc(1,1,i),[3,1,2]),permute(-Vmarkers.r_ajc(3,1,i),[3,1,2]),permute(Vmarkers.r_ajc(2,1,i),[3,1,2]), ...
                'Marker','.','Color','Blue','Markersize',20);
        end
        if isfield(Vmarkers,'l_kjc')
            plot3(permute(Vmarkers.l_kjc(1,1,i),[3,1,2]),permute(-Vmarkers.l_kjc(3,1,i),[3,1,2]),permute(Vmarkers.l_kjc(2,1,i),[3,1,2]), ...
                'Marker','.','Color','Blue','Markersize',20);
        end
        if isfield(Vmarkers,'l_ajc')
            plot3(permute(Vmarkers.l_ajc(1,1,i),[3,1,2]),permute(-Vmarkers.l_ajc(3,1,i),[3,1,2]),permute(Vmarkers.l_ajc(2,1,i),[3,1,2]), ...
                'Marker','.','Color','Blue','Markersize',20);
        end

        plot3([permute(Markers.sacrum(1,1,i),[3,1,2]),permute(Markers.r_asis(1,1,i),[3,1,2])], ...
            [permute(-Markers.sacrum(3,1,i),[3,1,2]),permute(-Markers.r_asis(3,1,i),[3,1,2])], ...
            [permute(Markers.sacrum(2,1,i),[3,1,2]),permute(Markers.r_asis(2,1,i),[3,1,2])], ...
            'Linestyle','-','Color','red','Linewidth',1);
        plot3([permute(Markers.sacrum(1,1,i),[3,1,2]),permute(Markers.l_asis(1,1,i),[3,1,2])], ...
            [permute(-Markers.sacrum(3,1,i),[3,1,2]),permute(-Markers.l_asis(3,1,i),[3,1,2])], ...
            [permute(Markers.sacrum(2,1,i),[3,1,2]),permute(Markers.l_asis(2,1,i),[3,1,2])], ...
            'Linestyle','-','Color','red','Linewidth',1);
        plot3([permute(Markers.r_asis(1,1,i),[3,1,2]),permute(Markers.l_asis(1,1,i),[3,1,2])], ...
            [permute(-Markers.r_asis(3,1,i),[3,1,2]),permute(-Markers.l_asis(3,1,i),[3,1,2])], ...
            [permute(Markers.r_asis(2,1,i),[3,1,2]),permute(Markers.l_asis(2,1,i),[3,1,2])], ...
            'Linestyle','-','Color','red','Linewidth',1);
        plot3([permute(Markers.r_thigh(1,1,i),[3,1,2]),permute(Markers.r_knee_1(1,1,i),[3,1,2])], ...
            [permute(-Markers.r_thigh(3,1,i),[3,1,2]),permute(-Markers.r_knee_1(3,1,i),[3,1,2])], ...
            [permute(Markers.r_thigh(2,1,i),[3,1,2]),permute(Markers.r_knee_1(2,1,i),[3,1,2])], ...
            'Linestyle','-','Color','red','Linewidth',1);
        plot3([permute(Markers.r_thigh(1,1,i),[3,1,2]),permute(Markers.r_bar_1(1,1,i),[3,1,2])], ...
            [permute(-Markers.r_thigh(3,1,i),[3,1,2]),permute(-Markers.r_bar_1(3,1,i),[3,1,2])], ...
            [permute(Markers.r_thigh(2,1,i),[3,1,2]),permute(Markers.r_bar_1(2,1,i),[3,1,2])], ...
            'Linestyle','-','Color','red','Linewidth',1);
        plot3([permute(Markers.r_bar_1(1,1,i),[3,1,2]),permute(Markers.r_knee_1(1,1,i),[3,1,2])], ...
            [permute(-Markers.r_bar_1(3,1,i),[3,1,2]),permute(-Markers.r_knee_1(3,1,i),[3,1,2])], ...
            [permute(Markers.r_bar_1(2,1,i),[3,1,2]),permute(Markers.r_knee_1(2,1,i),[3,1,2])], ...
            'Linestyle','-','Color','red','Linewidth',1);
        plot3([permute(Markers.r_knee_2(1,1,i),[3,1,2]),permute(Markers.r_mall(1,1,i),[3,1,2])], ...
            [permute(-Markers.r_knee_2(3,1,i),[3,1,2]),permute(-Markers.r_mall(3,1,i),[3,1,2])], ...
            [permute(Markers.r_knee_2(2,1,i),[3,1,2]),permute(Markers.r_mall(2,1,i),[3,1,2])], ...
            'Linestyle','-','Color','red','Linewidth',1);
        plot3([permute(Markers.r_knee_2(1,1,i),[3,1,2]),permute(Markers.r_bar_2(1,1,i),[3,1,2])], ...
            [permute(-Markers.r_knee_2(3,1,i),[3,1,2]),permute(-Markers.r_bar_2(3,1,i),[3,1,2])], ...
            [permute(Markers.r_knee_2(2,1,i),[3,1,2]),permute(Markers.r_bar_2(2,1,i),[3,1,2])], ...
            'Linestyle','-','Color','red','Linewidth',1);
        plot3([permute(Markers.r_bar_2(1,1,i),[3,1,2]),permute(Markers.r_mall(1,1,i),[3,1,2])], ...
            [permute(-Markers.r_bar_2(3,1,i),[3,1,2]),permute(-Markers.r_mall(3,1,i),[3,1,2])], ...
            [permute(Markers.r_bar_2(2,1,i),[3,1,2]),permute(Markers.r_mall(2,1,i),[3,1,2])], ...
            'Linestyle','-','Color','red','Linewidth',1);
        plot3([permute(Markers.l_thigh(1,1,i),[3,1,2]),permute(Markers.l_knee_1(1,1,i),[3,1,2])], ...
            [permute(-Markers.l_thigh(3,1,i),[3,1,2]),permute(-Markers.l_knee_1(3,1,i),[3,1,2])], ...
            [permute(Markers.l_thigh(2,1,i),[3,1,2]),permute(Markers.l_knee_1(2,1,i),[3,1,2])], ...
            'Linestyle','-','Color','red','Linewidth',1);
        plot3([permute(Markers.l_thigh(1,1,i),[3,1,2]),permute(Markers.l_bar_1(1,1,i),[3,1,2])], ...
            [permute(-Markers.l_thigh(3,1,i),[3,1,2]),permute(-Markers.l_bar_1(3,1,i),[3,1,2])], ...
            [permute(Markers.l_thigh(2,1,i),[3,1,2]),permute(Markers.l_bar_1(2,1,i),[3,1,2])], ...
            'Linestyle','-','Color','red','Linewidth',1);
        plot3([permute(Markers.l_bar_1(1,1,i),[3,1,2]),permute(Markers.l_knee_1(1,1,i),[3,1,2])], ...
            [permute(-Markers.l_bar_1(3,1,i),[3,1,2]),permute(-Markers.l_knee_1(3,1,i),[3,1,2])], ...
            [permute(Markers.l_bar_1(2,1,i),[3,1,2]),permute(Markers.l_knee_1(2,1,i),[3,1,2])], ...
            'Linestyle','-','Color','red','Linewidth',1);
        plot3([permute(Markers.l_knee_2(1,1,i),[3,1,2]),permute(Markers.l_mall(1,1,i),[3,1,2])], ...
            [permute(-Markers.l_knee_2(3,1,i),[3,1,2]),permute(-Markers.l_mall(3,1,i),[3,1,2])], ...
            [permute(Markers.l_knee_2(2,1,i),[3,1,2]),permute(Markers.l_mall(2,1,i),[3,1,2])], ...
            'Linestyle','-','Color','red','Linewidth',1);
        plot3([permute(Markers.l_knee_2(1,1,i),[3,1,2]),permute(Markers.l_bar_2(1,1,i),[3,1,2])], ...
            [permute(-Markers.l_knee_2(3,1,i),[3,1,2]),permute(-Markers.l_bar_2(3,1,i),[3,1,2])], ...
            [permute(Markers.l_knee_2(2,1,i),[3,1,2]),permute(Markers.l_bar_2(2,1,i),[3,1,2])], ...
            'Linestyle','-','Color','red','Linewidth',1);
        plot3([permute(Markers.l_bar_2(1,1,i),[3,1,2]),permute(Markers.l_mall(1,1,i),[3,1,2])], ...
            [permute(-Markers.l_bar_2(3,1,i),[3,1,2]),permute(-Markers.l_mall(3,1,i),[3,1,2])], ...
            [permute(Markers.l_bar_2(2,1,i),[3,1,2]),permute(Markers.l_mall(2,1,i),[3,1,2])], ...
            'Linestyle','-','Color','red','Linewidth',1);

    elseif strcmp(system,'Qualisys')

        plot3(permute(Markers.R_IPS(1,1,i),[3,1,2]),permute(-Markers.R_IPS(3,1,i),[3,1,2]),permute(Markers.R_IPS(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Red','Markersize',20);
        plot3(permute(Markers.L_IPS(1,1,i),[3,1,2]),permute(-Markers.L_IPS(3,1,i),[3,1,2]),permute(Markers.L_IPS(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Red','Markersize',20);
        plot3(permute(Markers.R_IAS(1,1,i),[3,1,2]),permute(-Markers.R_IAS(3,1,i),[3,1,2]),permute(Markers.R_IAS(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Red','Markersize',20);
        plot3(permute(Markers.L_IAS(1,1,i),[3,1,2]),permute(-Markers.L_IAS(3,1,i),[3,1,2]),permute(Markers.L_IAS(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Red','Markersize',20);
        plot3(permute(Markers.R_FTC(1,1,i),[3,1,2]),permute(-Markers.R_FTC(3,1,i),[3,1,2]),permute(Markers.R_FTC(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Red','Markersize',20);
        plot3(permute(Markers.R_FLE(1,1,i),[3,1,2]),permute(-Markers.R_FLE(3,1,i),[3,1,2]),permute(Markers.R_FLE(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Red','Markersize',20);
        if isfield(Markers,'R_FME')
            plot3(permute(Markers.R_FME(1,1,i),[3,1,2]),permute(-Markers.R_FME(3,1,i),[3,1,2]),permute(Markers.R_FME(2,1,i),[3,1,2]), ...
                'Marker','.','Color','Green','Markersize',20);
        end
        plot3(permute(Markers.R_FAX(1,1,i),[3,1,2]),permute(-Markers.R_FAX(3,1,i),[3,1,2]),permute(Markers.R_FAX(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Red','Markersize',20);
        plot3(permute(Markers.R_TTC(1,1,i),[3,1,2]),permute(-Markers.R_TTC(3,1,i),[3,1,2]),permute(Markers.R_TTC(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Red','Markersize',20);
        plot3(permute(Markers.R_FAL(1,1,i),[3,1,2]),permute(-Markers.R_FAL(3,1,i),[3,1,2]),permute(Markers.R_FAL(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Red','Markersize',20);
        if isfield(Markers,'R_TAM')
            plot3(permute(Markers.R_TAM(1,1,i),[3,1,2]),permute(-Markers.R_TAM(3,1,i),[3,1,2]),permute(Markers.R_TAM(2,1,i),[3,1,2]), ...
                'Marker','.','Color','Green','Markersize',20);
        end
        plot3(permute(Markers.R_FCC(1,1,i),[3,1,2]),permute(-Markers.R_FCC(3,1,i),[3,1,2]),permute(Markers.R_FCC(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Red','Markersize',20);
        plot3(permute(Markers.R_FM1(1,1,i),[3,1,2]),permute(-Markers.R_FM1(3,1,i),[3,1,2]),permute(Markers.R_FM1(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Red','Markersize',20);
        if isfield(Markers,'R_FM2')
            plot3(permute(Markers.R_FM2(1,1,i),[3,1,2]),permute(-Markers.R_FM2(3,1,i),[3,1,2]),permute(Markers.R_FM2(2,1,i),[3,1,2]), ...
                'Marker','.','Color','Green','Markersize',20);
        end
        plot3(permute(Markers.R_FM5(1,1,i),[3,1,2]),permute(-Markers.R_FM5(3,1,i),[3,1,2]),permute(Markers.R_FM5(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Red','Markersize',20);
        plot3(permute(Markers.L_FTC(1,1,i),[3,1,2]),permute(-Markers.L_FTC(3,1,i),[3,1,2]),permute(Markers.L_FTC(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Red','Markersize',20);
        plot3(permute(Markers.L_FLE(1,1,i),[3,1,2]),permute(-Markers.L_FLE(3,1,i),[3,1,2]),permute(Markers.L_FLE(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Red','Markersize',20);
        if isfield(Markers,'L_FME')
            plot3(permute(Markers.L_FME(1,1,i),[3,1,2]),permute(-Markers.L_FME(3,1,i),[3,1,2]),permute(Markers.L_FME(2,1,i),[3,1,2]), ...
                'Marker','.','Color','Green','Markersize',20);
        end
        plot3(permute(Markers.L_FAX(1,1,i),[3,1,2]),permute(-Markers.L_FAX(3,1,i),[3,1,2]),permute(Markers.L_FAX(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Red','Markersize',20);
        plot3(permute(Markers.L_TTC(1,1,i),[3,1,2]),permute(-Markers.L_TTC(3,1,i),[3,1,2]),permute(Markers.L_TTC(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Red','Markersize',20);
        plot3(permute(Markers.L_FAL(1,1,i),[3,1,2]),permute(-Markers.L_FAL(3,1,i),[3,1,2]),permute(Markers.L_FAL(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Red','Markersize',20);
        if isfield(Markers,'L_TAM')
            plot3(permute(Markers.L_TAM(1,1,i),[3,1,2]),permute(-Markers.L_TAM(3,1,i),[3,1,2]),permute(Markers.L_TAM(2,1,i),[3,1,2]), ...
                'Marker','.','Color','Green','Markersize',20);
        end
        plot3(permute(Markers.L_FCC(1,1,i),[3,1,2]),permute(-Markers.L_FCC(3,1,i),[3,1,2]),permute(Markers.L_FCC(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Red','Markersize',20);
        plot3(permute(Markers.L_FM1(1,1,i),[3,1,2]),permute(-Markers.L_FM1(3,1,i),[3,1,2]),permute(Markers.L_FM1(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Red','Markersize',20);
        if isfield(Markers,'L_FM2')
            plot3(permute(Markers.L_FM2(1,1,i),[3,1,2]),permute(-Markers.L_FM2(3,1,i),[3,1,2]),permute(Markers.L_FM2(2,1,i),[3,1,2]), ...
                'Marker','.','Color','Green','Markersize',20);
        end
        plot3(permute(Markers.L_FM5(1,1,i),[3,1,2]),permute(-Markers.L_FM5(3,1,i),[3,1,2]),permute(Markers.L_FM5(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Red','Markersize',20);

        plot3(permute(Vmarkers.ljc(1,1,i),[3,1,2]),permute(-Vmarkers.ljc(3,1,i),[3,1,2]),permute(Vmarkers.ljc(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Blue','Markersize',20);
        plot3(permute(Vmarkers.r_hjc(1,1,i),[3,1,2]),permute(-Vmarkers.r_hjc(3,1,i),[3,1,2]),permute(Vmarkers.r_hjc(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Blue','Markersize',20);
        plot3(permute(Vmarkers.l_hjc(1,1,i),[3,1,2]),permute(-Vmarkers.l_hjc(3,1,i),[3,1,2]),permute(Vmarkers.l_hjc(2,1,i),[3,1,2]), ...
            'Marker','.','Color','Blue','Markersize',20);
        if isfield(Vmarkers,'r_kjc')
            plot3(permute(Vmarkers.r_kjc(1,1,i),[3,1,2]),permute(-Vmarkers.r_kjc(3,1,i),[3,1,2]),permute(Vmarkers.r_kjc(2,1,i),[3,1,2]), ...
                'Marker','.','Color','Blue','Markersize',20);
        end
        if isfield(Vmarkers,'r_ajc')
            plot3(permute(Vmarkers.r_ajc(1,1,i),[3,1,2]),permute(-Vmarkers.r_ajc(3,1,i),[3,1,2]),permute(Vmarkers.r_ajc(2,1,i),[3,1,2]), ...
                'Marker','.','Color','Blue','Markersize',20);
        end
        if isfield(Vmarkers,'l_kjc')
            plot3(permute(Vmarkers.l_kjc(1,1,i),[3,1,2]),permute(-Vmarkers.l_kjc(3,1,i),[3,1,2]),permute(Vmarkers.l_kjc(2,1,i),[3,1,2]), ...
                'Marker','.','Color','Blue','Markersize',20);
        end
        if isfield(Vmarkers,'l_ajc')
            plot3(permute(Vmarkers.l_ajc(1,1,i),[3,1,2]),permute(-Vmarkers.l_ajc(3,1,i),[3,1,2]),permute(Vmarkers.l_ajc(2,1,i),[3,1,2]), ...
                'Marker','.','Color','Blue','Markersize',20);
        end

        plot3([permute(Markers.R_IPS(1,1,i),[3,1,2]),permute(Markers.R_IAS(1,1,i),[3,1,2])], ...
            [permute(-Markers.R_IPS(3,1,i),[3,1,2]),permute(-Markers.R_IAS(3,1,i),[3,1,2])], ...
            [permute(Markers.R_IPS(2,1,i),[3,1,2]),permute(Markers.R_IAS(2,1,i),[3,1,2])], ...
            'Linestyle','-','Color','red','Linewidth',1);
        plot3([permute(Markers.R_IPS(1,1,i),[3,1,2]),permute(Markers.L_IPS(1,1,i),[3,1,2])], ...
            [permute(-Markers.R_IPS(3,1,i),[3,1,2]),permute(-Markers.L_IPS(3,1,i),[3,1,2])], ...
            [permute(Markers.R_IPS(2,1,i),[3,1,2]),permute(Markers.L_IPS(2,1,i),[3,1,2])], ...
            'Linestyle','-','Color','red','Linewidth',1);
        plot3([permute(Markers.L_IAS(1,1,i),[3,1,2]),permute(Markers.L_IPS(1,1,i),[3,1,2])], ...
            [permute(-Markers.L_IAS(3,1,i),[3,1,2]),permute(-Markers.L_IPS(3,1,i),[3,1,2])], ...
            [permute(Markers.L_IAS(2,1,i),[3,1,2]),permute(Markers.L_IPS(2,1,i),[3,1,2])], ...
            'Linestyle','-','Color','red','Linewidth',1);
        plot3([permute(Markers.L_IAS(1,1,i),[3,1,2]),permute(Markers.R_IAS(1,1,i),[3,1,2])], ...
            [permute(-Markers.L_IAS(3,1,i),[3,1,2]),permute(-Markers.R_IAS(3,1,i),[3,1,2])], ...
            [permute(Markers.L_IAS(2,1,i),[3,1,2]),permute(Markers.R_IAS(2,1,i),[3,1,2])], ...
            'Linestyle','-','Color','red','Linewidth',1);
        plot3([permute(Markers.R_FTC(1,1,i),[3,1,2]),permute(Markers.R_FLE(1,1,i),[3,1,2])], ...
            [permute(-Markers.R_FTC(3,1,i),[3,1,2]),permute(-Markers.R_FLE(3,1,i),[3,1,2])], ...
            [permute(Markers.R_FTC(2,1,i),[3,1,2]),permute(Markers.R_FLE(2,1,i),[3,1,2])], ...
            'Linestyle','-','Color','red','Linewidth',1);
        plot3([permute(Markers.L_FTC(1,1,i),[3,1,2]),permute(Markers.L_FLE(1,1,i),[3,1,2])], ...
            [permute(-Markers.L_FTC(3,1,i),[3,1,2]),permute(-Markers.L_FLE(3,1,i),[3,1,2])], ...
            [permute(Markers.L_FTC(2,1,i),[3,1,2]),permute(Markers.L_FLE(2,1,i),[3,1,2])], ...
            'Linestyle','-','Color','red','Linewidth',1);
        plot3([permute(Markers.R_FAX(1,1,i),[3,1,2]),permute(Markers.R_TTC(1,1,i),[3,1,2])], ...
            [permute(-Markers.R_FAX(3,1,i),[3,1,2]),permute(-Markers.R_TTC(3,1,i),[3,1,2])], ...
            [permute(Markers.R_FAX(2,1,i),[3,1,2]),permute(Markers.R_TTC(2,1,i),[3,1,2])], ...
            'Linestyle','-','Color','red','Linewidth',1);
        plot3([permute(Markers.R_FAX(1,1,i),[3,1,2]),permute(Markers.R_FAL(1,1,i),[3,1,2])], ...
            [permute(-Markers.R_FAX(3,1,i),[3,1,2]),permute(-Markers.R_FAL(3,1,i),[3,1,2])], ...
            [permute(Markers.R_FAX(2,1,i),[3,1,2]),permute(Markers.R_FAL(2,1,i),[3,1,2])], ...
            'Linestyle','-','Color','red','Linewidth',1);
        plot3([permute(Markers.R_TTC(1,1,i),[3,1,2]),permute(Markers.R_FAL(1,1,i),[3,1,2])], ...
            [permute(-Markers.R_TTC(3,1,i),[3,1,2]),permute(-Markers.R_FAL(3,1,i),[3,1,2])], ...
            [permute(Markers.R_TTC(2,1,i),[3,1,2]),permute(Markers.R_FAL(2,1,i),[3,1,2])], ...
            'Linestyle','-','Color','red','Linewidth',1);
        plot3([permute(Markers.L_FAX(1,1,i),[3,1,2]),permute(Markers.L_TTC(1,1,i),[3,1,2])], ...
            [permute(-Markers.L_FAX(3,1,i),[3,1,2]),permute(-Markers.L_TTC(3,1,i),[3,1,2])], ...
            [permute(Markers.L_FAX(2,1,i),[3,1,2]),permute(Markers.L_TTC(2,1,i),[3,1,2])], ...
            'Linestyle','-','Color','red','Linewidth',1);
        plot3([permute(Markers.L_FAX(1,1,i),[3,1,2]),permute(Markers.L_FAL(1,1,i),[3,1,2])], ...
            [permute(-Markers.L_FAX(3,1,i),[3,1,2]),permute(-Markers.L_FAL(3,1,i),[3,1,2])], ...
            [permute(Markers.L_FAX(2,1,i),[3,1,2]),permute(Markers.L_FAL(2,1,i),[3,1,2])], ...
            'Linestyle','-','Color','red','Linewidth',1);
        plot3([permute(Markers.L_TTC(1,1,i),[3,1,2]),permute(Markers.L_FAL(1,1,i),[3,1,2])], ...
            [permute(-Markers.L_TTC(3,1,i),[3,1,2]),permute(-Markers.L_FAL(3,1,i),[3,1,2])], ...
            [permute(Markers.L_TTC(2,1,i),[3,1,2]),permute(Markers.L_FAL(2,1,i),[3,1,2])], ...
            'Linestyle','-','Color','red','Linewidth',1);
        plot3([permute(Markers.R_FCC(1,1,i),[3,1,2]),permute(Markers.R_FM1(1,1,i),[3,1,2])], ...
            [permute(-Markers.R_FCC(3,1,i),[3,1,2]),permute(-Markers.R_FM1(3,1,i),[3,1,2])], ...
            [permute(Markers.R_FCC(2,1,i),[3,1,2]),permute(Markers.R_FM1(2,1,i),[3,1,2])], ...
            'Linestyle','-','Color','red','Linewidth',1);
        plot3([permute(Markers.R_FCC(1,1,i),[3,1,2]),permute(Markers.R_FM5(1,1,i),[3,1,2])], ...
            [permute(-Markers.R_FCC(3,1,i),[3,1,2]),permute(-Markers.R_FM5(3,1,i),[3,1,2])], ...
            [permute(Markers.R_FCC(2,1,i),[3,1,2]),permute(Markers.R_FM5(2,1,i),[3,1,2])], ...
            'Linestyle','-','Color','red','Linewidth',1);
        plot3([permute(Markers.R_FM1(1,1,i),[3,1,2]),permute(Markers.R_FM5(1,1,i),[3,1,2])], ...
            [permute(-Markers.R_FM1(3,1,i),[3,1,2]),permute(-Markers.R_FM5(3,1,i),[3,1,2])], ...
            [permute(Markers.R_FM1(2,1,i),[3,1,2]),permute(Markers.R_FM5(2,1,i),[3,1,2])], ...
            'Linestyle','-','Color','red','Linewidth',1);    
        plot3([permute(Markers.L_FCC(1,1,i),[3,1,2]),permute(Markers.L_FM1(1,1,i),[3,1,2])], ...
            [permute(-Markers.L_FCC(3,1,i),[3,1,2]),permute(-Markers.L_FM1(3,1,i),[3,1,2])], ...
            [permute(Markers.L_FCC(2,1,i),[3,1,2]),permute(Markers.L_FM1(2,1,i),[3,1,2])], ...
            'Linestyle','-','Color','red','Linewidth',1);
        plot3([permute(Markers.L_FCC(1,1,i),[3,1,2]),permute(Markers.L_FM5(1,1,i),[3,1,2])], ...
            [permute(-Markers.L_FCC(3,1,i),[3,1,2]),permute(-Markers.L_FM5(3,1,i),[3,1,2])], ...
            [permute(Markers.L_FCC(2,1,i),[3,1,2]),permute(Markers.L_FM5(2,1,i),[3,1,2])], ...
            'Linestyle','-','Color','red','Linewidth',1);
        plot3([permute(Markers.L_FM1(1,1,i),[3,1,2]),permute(Markers.L_FM5(1,1,i),[3,1,2])], ...
            [permute(-Markers.L_FM1(3,1,i),[3,1,2]),permute(-Markers.L_FM5(3,1,i),[3,1,2])], ...
            [permute(Markers.L_FM1(2,1,i),[3,1,2]),permute(Markers.L_FM5(2,1,i),[3,1,2])], ...
            'Linestyle','-','Color','red','Linewidth',1);

    end
   
    pause(0.01);
    if i~= n
        clf(fig);
    end
    
end