% =========================================================================
% REHAZENTER TOOLBOX
% =========================================================================
% File name:    sqlStoreExamination
% -------------------------------------------------------------------------
% Subject:      Store examination information in the database
% -------------------------------------------------------------------------
% Inputs:       - Patient (structure)
%               - Session (structure)
%               - Examination (structure)
%               - db (structure)
% Outputs:      - None
% -------------------------------------------------------------------------
% Author: F. Moissenet, C. Schreiber, A. Naaim
% Date of creation: 12/12/2014
% Version: 1
% -------------------------------------------------------------------------
% Updates: - 
% =========================================================================

function [] = sqlStoreExamination(Patient,Session,Examination,db)

% =========================================================================
% Get patientid from database
% =========================================================================
merge = strcat('SELECT `patientid` FROM `patient` WHERE `lastname` ="',...
    Patient.lastname,'" && firstname ="',...
    Patient.firstname,'" && birthdate ="',...
    Patient.birthdate,'"');
db.prepareStatement(merge, 10001);
finder1 = db.query();

% =========================================================================
% Get sessionid from database
% =========================================================================
merge = strcat('SELECT `sessionid` FROM `session` WHERE `patientid` ="',...
    num2str(finder1.patientid),'" && date ="',Session.date,'"');
db.prepareStatement(merge, 10001);
finder2 = db.query();

% =========================================================================
% Check if the examination exist in the database
% test = check sessionid
% =========================================================================
merge = strcat('SELECT * FROM `examination` WHERE `sessionid` ="',...
    num2str(finder2.sessionid),'"');
db.prepareStatement(merge);
finder3 = db.query();

% =========================================================================
% Add examination information
% =========================================================================
if size(finder3.sessionid,1) == 0   
    merge = strcat(['INSERT INTO `examination`',...
        '(`patientid`,`sessionid`,',...
        '`rprom_hip_flexion`,',...                                         % PROM / HIP / RIGHT
        '`rprom_hip_extensionKneeExt`,',...
        '`rprom_hip_extensionKneeFlex`,',...
        '`rprom_hip_extensionThomas`,',...
        '`rprom_hip_abductionHipFlexKneeFlex`,',...
        '`rprom_hip_abductionHipExtKneeFlex`,',...
        '`rprom_hip_abductionHipExtKneeExt`,',...
        '`rprom_hip_adduction`,',...
        '`rprom_hip_rotationIntDD`,',...
        '`rprom_hip_rotationExtDD`,',...
        '`rprom_hip_rotationIntDV`,',...
        '`rprom_hip_rotationExtDV`,',...
        '`rprom_hip_antetorsionFemorale`,',...
        '`lprom_hip_flexion`,',...                                         % PROM / HIP / LEFT
        '`lprom_hip_extensionKneeExt`,',...
        '`lprom_hip_extensionKneeFlex`,',...
        '`lprom_hip_extensionThomas`,',...
        '`lprom_hip_abductionHipFlexKneeFlex`,',...
        '`lprom_hip_abductionHipExtKneeFlex`,',...
        '`lprom_hip_abductionHipExtKneeExt`,',...
        '`lprom_hip_adduction`,',...
        '`lprom_hip_rotationIntDD`,',...
        '`lprom_hip_rotationExtDD`,',...
        '`lprom_hip_rotationIntDV`,',...
        '`lprom_hip_rotationExtDV`,',...
        '`lprom_hip_antetorsionFemorale`,',...
        '`rprom_knee_flexion`,',...                                        % PROM / KNEE / RIGHT
        '`rprom_knee_extension`,',...
        '`rprom_knee_raideurArt`,',...
        '`rprom_knee_angleMort`,',...
        '`rprom_knee_rotuleHte`,',...
        '`rprom_knee_cocontractions`,',...
        '`rprom_knee_anglePopUni`,',...
        '`rprom_knee_anglePopBi`,',...
        '`lprom_knee_flexion`,',...                                        % PROM / KNEE / LEFT
        '`lprom_knee_extension`,',...
        '`lprom_knee_raideurArt`,',...
        '`lprom_knee_angleMort`,',...
        '`lprom_knee_rotuleHte`,',...
        '`lprom_knee_cocontractions`,',...
        '`lprom_knee_anglePopUni`,',...
        '`lprom_knee_anglePopBi`,',...
        '`rprom_ankle_plantarFlex`,',...                                   % PROM / ANKLE / RIGHT
        '`rprom_ankle_dorsiFlexSilverskold`,',...
        '`rprom_ankle_dorsiFlexKneeExt`,',...
        '`rprom_ankle_dorsiFlexKneeFlex`,',...
        '`rprom_ankle_dorsiFlexMaxCharge`,',...
        '`lprom_ankle_plantarFlex`,',...                                   % PROM / ANKLE / LEFT
        '`lprom_ankle_dorsiFlexSilverskold`,',...
        '`lprom_ankle_dorsiFlexKneeExt`,',...
        '`lprom_ankle_dorsiFlexKneeFlex`,',...
        '`lprom_ankle_dorsiFlexMaxCharge`,',...
        '`rprom_foot_axeCruroped`,',...                                    % PROM / FOOT / RIGHT
        '`rprom_foot_axeBiMalleol`,',... 
        '`rprom_foot_VRspontane`,',... 
        '`rprom_foot_VGspontane`,',... 
        '`rprom_foot_VRcharge`,',... 
        '`rprom_foot_VGcharge`,',...
        '`rprom_foot_dislocMedioTars`,',... 
        '`rprom_foot_retractFlexOrteils`,',...  
        '`rprom_foot_piedPlat`,',...  
        '`rprom_foot_piedCavus`,',...  
        '`rprom_foot_piedConvexe`,',...  
        '`rprom_foot_adductusAvPied`,',...  
        '`rprom_foot_abductusAvPied`,',...  
        '`rprom_foot_halluxValgus`,',...   
        '`rprom_foot_halluxFlexus`,',...   
        '`rprom_foot_halluxRigidus`,',...
        '`rprom_foot_griffePassive`,',...
        '`rprom_foot_griffeDynamic`,',...
        '`lprom_foot_axeCruroped`,',...                                    % PROM / FOOT / LEFT
        '`lprom_foot_axeBiMalleol`,',... 
        '`lprom_foot_VRspontane`,',... 
        '`lprom_foot_VGspontane`,',... 
        '`lprom_foot_VRcharge`,',... 
        '`lprom_foot_VGcharge`,',...
        '`lprom_foot_dislocMedioTars`,',... 
        '`lprom_foot_retractFlexOrteils`,',...  
        '`lprom_foot_piedPlat`,',...  
        '`lprom_foot_piedCavus`,',...  
        '`lprom_foot_piedConvexe`,',...  
        '`lprom_foot_adductusAvPied`,',...  
        '`lprom_foot_abductusAvPied`,',...  
        '`lprom_foot_halluxValgus`,',...   
        '`lprom_foot_halluxFlexus`,',...   
        '`lprom_foot_halluxRigidus`,',...
        '`lprom_foot_griffePassive`,',...
        '`lprom_foot_griffeDynamic`,',...
        '`rforce_hip_flechisseursDD`,',...                                 % FORCE / HIP / RIGHT                            
        '`rforce_hip_extenseurs`,',...                                 
        '`rforce_hip_abducteurs`,',...                                 
        '`rforce_hip_adducteurs`,',...                                 
        '`rforce_hip_rotInt`,',...                                 
        '`rforce_hip_rotExt`,',...   
        '`lforce_hip_flechisseursDD`,',...                                 % FORCE / HIP / LEFT                                
        '`lforce_hip_extenseurs`,',...                                 
        '`lforce_hip_abducteurs`,',...                                 
        '`lforce_hip_adducteurs`,',...                                 
        '`lforce_hip_rotInt`,',...                                 
        '`lforce_hip_rotExt`,',...                                 
        '`rforce_knee_flechisseurs`,',...                                  % FORCE / KNEE / RIGHT                                   
        '`rforce_knee_extenseurs`,',...                             
        '`lforce_knee_flechisseurs`,',...                                  % FORCE / KNEE / LEFT                                   
        '`lforce_knee_extenseurs`,',...                              
        '`rforce_ankle_tibialisAnt`,',...                                  % FORCE / ANKLE / RIGHT                            
        '`rforce_ankle_extDigLong`,',...                            
        '`rforce_ankle_extHalLong`,',...                            
        '`rforce_ankle_peroneus`,',...                            
        '`rforce_ankle_tibialisPost`,',...                            
        '`rforce_ankle_gastSol`,',...                            
        '`rforce_ankle_flexDigLong`,',...                            
        '`rforce_ankle_flexHalLong`,',...
        '`lforce_ankle_tibialisAnt`,',...                                  % FORCE / ANKLE / LEFT                            
        '`lforce_ankle_extDigLong`,',...                            
        '`lforce_ankle_extHalLong`,',...                            
        '`lforce_ankle_peroneus`,',...                            
        '`lforce_ankle_tibialisPost`,',...                            
        '`lforce_ankle_gastSol`,',...                            
        '`lforce_ankle_flexDigLong`,',...                            
        '`lforce_ankle_flexHalLong`,',... 
        '`rselectivity_hip_flechisseursDD`,',...                           % SELECTIVITY / HIP / RIGHT 
        '`rselectivity_hip_extenseurs`,',... 
        '`rselectivity_hip_abducteurs`,',... 
        '`rselectivity_hip_adducteurs`,',... 
        '`rselectivity_hip_rotInt`,',... 
        '`rselectivity_hip_rotExt`,',...    
        '`lselectivity_hip_flechisseursDD`,',...                           % SELECTIVITY / HIP / LEFT 
        '`lselectivity_hip_extenseurs`,',... 
        '`lselectivity_hip_abducteurs`,',... 
        '`lselectivity_hip_adducteurs`,',... 
        '`lselectivity_hip_rotInt`,',... 
        '`lselectivity_hip_rotExt`,',...          
        '`rselectivity_knee_flechisseurs`,',...                            % SELECTIVITY / KNEE / RIGHT    
        '`rselectivity_knee_extenseurs`,',...      
        '`lselectivity_knee_flechisseurs`,',...                            % SELECTIVITY / KNEE / LEFT    
        '`lselectivity_knee_extenseurs`,',...    
        '`rselectivity_ankle_boyd`,',...                                   % SELECTIVITY / ANKLE / RIGHT   
        '`rselectivity_ankle_confusionTest`,',...    
        '`rselectivity_ankle_peroneus`,',...    
        '`rselectivity_ankle_tibialisPost`,',...    
        '`rselectivity_ankle_gastSol`,',...    
        '`rselectivity_ankle_flexDigLong`,',...    
        '`rselectivity_ankle_flexHalLong`,',...     
        '`lselectivity_ankle_boyd`,',...                                   % SELECTIVITY / ANKLE / LEFT   
        '`lselectivity_ankle_confusionTest`,',...    
        '`lselectivity_ankle_peroneus`,',...    
        '`lselectivity_ankle_tibialisPost`,',...    
        '`lselectivity_ankle_gastSol`,',...    
        '`lselectivity_ankle_flexDigLong`,',...    
        '`lselectivity_ankle_flexHalLong`,',...   
        '`rspasticity_ashworth_hip_flechisseursDD`,',...                   % SPASTICITY / ASHWORTH / HIP / RIGHT        
        '`rspasticity_ashworth_hip_duncanElyTest`,',...
        '`rspasticity_ashworth_hip_extenseurs`,',...
        '`rspasticity_ashworth_hip_abducteurs`,',...
        '`rspasticity_ashworth_hip_adducteurs`,',...
        '`rspasticity_ashworth_hip_rotInt`,',...
        '`rspasticity_ashworth_hip_rotExt`,',... 
        '`lspasticity_ashworth_hip_flechisseursDD`,',...                   % SPASTICITY / ASHWORTH / HIP / LEFT        
        '`lspasticity_ashworth_hip_duncanElyTest`,',...
        '`lspasticity_ashworth_hip_extenseurs`,',...
        '`lspasticity_ashworth_hip_abducteurs`,',...
        '`lspasticity_ashworth_hip_adducteurs`,',...
        '`lspasticity_ashworth_hip_rotInt`,',...
        '`lspasticity_ashworth_hip_rotExt`,',... 
        '`rspasticity_ashworth_knee_flechisseurs`,',...                    % SPASTICITY / ASHWORTH / KNEE / RIGHT
        '`rspasticity_ashworth_knee_extenseurs`,',...  
        '`lspasticity_ashworth_knee_flechisseurs`,',...                    % SPASTICITY / ASHWORTH / KNEE / LEFT
        '`lspasticity_ashworth_knee_extenseurs`,',...     
        '`rspasticity_ashworth_ankle_tibialisAnt`,',...                    % SPASTICITY / ASHWORTH / ANKLE / RIGHT   
        '`rspasticity_ashworth_ankle_extDigLong`,',...   
        '`rspasticity_ashworth_ankle_extHalLong`,',...   
        '`rspasticity_ashworth_ankle_peroneus`,',...   
        '`rspasticity_ashworth_ankle_tibialisPost`,',...   
        '`rspasticity_ashworth_ankle_gastSol`,',...   
        '`rspasticity_ashworth_ankle_flechisseurs`,',... 
        '`lspasticity_ashworth_ankle_tibialisAnt`,',...                    % SPASTICITY / ASHWORTH / ANKLE / LEFT   
        '`lspasticity_ashworth_ankle_extDigLong`,',...   
        '`lspasticity_ashworth_ankle_extHalLong`,',...   
        '`lspasticity_ashworth_ankle_peroneus`,',...   
        '`lspasticity_ashworth_ankle_tibialisPost`,',...   
        '`lspasticity_ashworth_ankle_gastSol`,',...   
        '`lspasticity_ashworth_ankle_flechisseurs`,',...         
        '`rspasticity_tardieu_hip_flechisseursDD`,',...                    % SPASTICITY / TARDIEU / HIP / RIGHT        
        '`rspasticity_tardieu_hip_duncanElyTest`,',...
        '`rspasticity_tardieu_hip_extenseurs`,',...
        '`rspasticity_tardieu_hip_abducteurs`,',...
        '`rspasticity_tardieu_hip_adducteurs`,',...
        '`rspasticity_tardieu_hip_rotInt`,',...
        '`rspasticity_tardieu_hip_rotExt`,',... 
        '`lspasticity_tardieu_hip_flechisseursDD`,',...                    % SPASTICITY / TARDIEU / HIP / LEFT        
        '`lspasticity_tardieu_hip_duncanElyTest`,',...
        '`lspasticity_tardieu_hip_extenseurs`,',...
        '`lspasticity_tardieu_hip_abducteurs`,',...
        '`lspasticity_tardieu_hip_adducteurs`,',...
        '`lspasticity_tardieu_hip_rotInt`,',...
        '`lspasticity_tardieu_hip_rotExt`,',... 
        '`rspasticity_tardieu_knee_flechisseurs`,',...                     % SPASTICITY / TARDIEU / KNEE / RIGHT
        '`rspasticity_tardieu_knee_extenseurs`,',...  
        '`lspasticity_tardieu_knee_flechisseurs`,',...                     % SPASTICITY / TARDIEU / KNEE / LEFT
        '`lspasticity_tardieu_knee_extenseurs`,',...     
        '`rspasticity_tardieu_ankle_tibialisAnt`,',...                     % SPASTICITY / TARDIEU / ANKLE / RIGHT   
        '`rspasticity_tardieu_ankle_extDigLong`,',...   
        '`rspasticity_tardieu_ankle_extHalLong`,',...   
        '`rspasticity_tardieu_ankle_peroneus`,',...   
        '`rspasticity_tardieu_ankle_tibialisPost`,',...   
        '`rspasticity_tardieu_ankle_gastSol`,',...      
        '`rspasticity_tardieu_ankle_r1r2`,',...  
        '`rspasticity_tardieu_ankle_flechisseurs`,',... 
        '`lspasticity_tardieu_ankle_tibialisAnt`,',...                     % SPASTICITY / TARDIEU / ANKLE / LEFT   
        '`lspasticity_tardieu_ankle_extDigLong`,',...   
        '`lspasticity_tardieu_ankle_extHalLong`,',...   
        '`lspasticity_tardieu_ankle_peroneus`,',...   
        '`lspasticity_tardieu_ankle_tibialisPost`,',...   
        '`lspasticity_tardieu_ankle_gastSol`,',...     
        '`lspasticity_tardieu_ankle_r1r2`,',...   
        '`lspasticity_tardieu_ankle_flechisseurs`,',...
        '`rsensitivity_superficielle`,',...                                % SENSITIVITY / RIGHT 
        '`rsensitivity_proprioceptive`,',...           
        '`lsensitivity_superficielle`,',...                                % SENSITIVITY / LEFT 
        '`lsensitivity_proprioceptive`,',...      
        '`scoliose`,',...                                                  % SCOLIOSE
        '`axeOccipital`,',...                                              % OCCIPITAL AXIS DEVIATION
        '`rleglength`,',...                                                % LEG LENGTH / RIGHT 
        '`lleglength`,',...                                                % LEG LENGTH / LEFT 
        '`group`) ',...                                                    % GROUP
        'VALUES ("'],...
        num2str(finder1.patientid),'","',...
        num2str(finder2.sessionid),'","',...
        Examination.Rprom.Hip.flexion,'","',...                            % PROM / HIP / RIGHT
        Examination.Rprom.Hip.extensionKneeExt,'","',...
        Examination.Rprom.Hip.extensionKneeFlex,'","',...
        Examination.Rprom.Hip.extensionThomas,'","',...
        Examination.Rprom.Hip.abductionHipFlexKneeFlex,'","',...
        Examination.Rprom.Hip.abductionHipExtKneeFlex,'","',...
        Examination.Rprom.Hip.abductionHipExtKneeExt,'","',...
        Examination.Rprom.Hip.adduction,'","',...
        Examination.Rprom.Hip.rotationIntDD,'","',...
        Examination.Rprom.Hip.rotationExtDD,'","',...
        Examination.Rprom.Hip.rotationIntDV,'","',...
        Examination.Rprom.Hip.rotationExtDV,'","',...
        Examination.Rprom.Hip.antetorsionFemorale,'","',...
        Examination.Lprom.Hip.flexion,'","',...                            % PROM / HIP / LEFT
        Examination.Lprom.Hip.extensionKneeExt,'","',...
        Examination.Lprom.Hip.extensionKneeFlex,'","',...
        Examination.Lprom.Hip.extensionThomas,'","',...
        Examination.Lprom.Hip.abductionHipFlexKneeFlex,'","',...
        Examination.Lprom.Hip.abductionHipExtKneeFlex,'","',...
        Examination.Lprom.Hip.abductionHipExtKneeExt,'","',...
        Examination.Lprom.Hip.adduction,'","',...
        Examination.Lprom.Hip.rotationIntDD,'","',...
        Examination.Lprom.Hip.rotationExtDD,'","',...
        Examination.Lprom.Hip.rotationIntDV,'","',...
        Examination.Lprom.Hip.rotationExtDV,'","',...
        Examination.Lprom.Hip.antetorsionFemorale,'","',...
        Examination.Rprom.Knee.flexion,'","',...                           % PROM / KNEE / RIGHT  
        Examination.Rprom.Knee.extension,'","',...  
        Examination.Rprom.Knee.raideurArt,'","',...  
        Examination.Rprom.Knee.angleMort,'","',...  
        Examination.Rprom.Knee.rotuleHte,'","',...  
        Examination.Rprom.Knee.cocontractions,'","',...  
        Examination.Rprom.Knee.anglePopUni,'","',...  
        Examination.Rprom.Knee.anglePopBi,'","',...  
        Examination.Lprom.Knee.flexion,'","',...                           % PROM / KNEE / LEFT  
        Examination.Lprom.Knee.extension,'","',...  
        Examination.Lprom.Knee.raideurArt,'","',...  
        Examination.Lprom.Knee.angleMort,'","',...  
        Examination.Lprom.Knee.rotuleHte,'","',...  
        Examination.Lprom.Knee.cocontractions,'","',...  
        Examination.Lprom.Knee.anglePopUni,'","',...  
        Examination.Lprom.Knee.anglePopBi,'","',... 
        Examination.Rprom.Ankle.plantarflex,'","',...                      % PROM / ANKLE / RIGHT   
        Examination.Rprom.Ankle.dorsiflexSilverskold,'","',...   
        Examination.Rprom.Ankle.dorsiflexKneeExt,'","',...   
        Examination.Rprom.Ankle.dorsiflexKneeFlex,'","',...   
        Examination.Rprom.Ankle.dorsiflexMaxCharge,'","',...   
        Examination.Lprom.Ankle.plantarflex,'","',...                      % PROM / ANKLE / LEFT   
        Examination.Lprom.Ankle.dorsiflexSilverskold,'","',...   
        Examination.Lprom.Ankle.dorsiflexKneeExt,'","',...   
        Examination.Lprom.Ankle.dorsiflexKneeFlex,'","',...   
        Examination.Lprom.Ankle.dorsiflexMaxCharge,'","',...  
        Examination.Rprom.Foot.axeCruroPed,'","',...                       % PROM / FOOT / RIGHT     
        Examination.Rprom.Foot.axeBiMalleol,'","',...    
        Examination.Rprom.Foot.VRspontane,'","',...    
        Examination.Rprom.Foot.VGspontane,'","',...    
        Examination.Rprom.Foot.VRcharge,'","',...    
        Examination.Rprom.Foot.VGcharge,'","',...    
        Examination.Rprom.Foot.dislocMedioTars,'","',...    
        Examination.Rprom.Foot.retractFlexOrteils,'","',...    
        Examination.Rprom.Foot.piedPlat,'","',...    
        Examination.Rprom.Foot.piedCavus,'","',...    
        Examination.Rprom.Foot.piedConvexe,'","',...    
        Examination.Rprom.Foot.adductusAvPied,'","',...    
        Examination.Rprom.Foot.abductusAvPied,'","',...    
        Examination.Rprom.Foot.halluxValgus,'","',...    
        Examination.Rprom.Foot.halluxFlexus,'","',...    
        Examination.Rprom.Foot.halluxRigidus,'","',...   
        Examination.Rprom.Foot.griffePassive,'","',...    
        Examination.Rprom.Foot.griffeDynamic,'","',...    
        Examination.Lprom.Foot.axeCruroPed,'","',...                       % PROM / FOOT / LEFT     
        Examination.Lprom.Foot.axeBiMalleol,'","',...    
        Examination.Lprom.Foot.VRspontane,'","',...    
        Examination.Lprom.Foot.VGspontane,'","',...    
        Examination.Lprom.Foot.VRcharge,'","',...    
        Examination.Lprom.Foot.VGcharge,'","',...    
        Examination.Lprom.Foot.dislocMedioTars,'","',...    
        Examination.Lprom.Foot.retractFlexOrteils,'","',...    
        Examination.Lprom.Foot.piedPlat,'","',...    
        Examination.Lprom.Foot.piedCavus,'","',...    
        Examination.Lprom.Foot.piedConvexe,'","',...    
        Examination.Lprom.Foot.adductusAvPied,'","',...    
        Examination.Lprom.Foot.abductusAvPied,'","',...    
        Examination.Lprom.Foot.halluxValgus,'","',...    
        Examination.Lprom.Foot.halluxFlexus,'","',...    
        Examination.Lprom.Foot.halluxRigidus,'","',...  
        Examination.Lprom.Foot.griffePassive,'","',...    
        Examination.Lprom.Foot.griffeDynamic,'","',... 
        Examination.Rforce.Hip.flechisseursDD,'","',...                    % FORCE / HIP / RIGHT 
        Examination.Rforce.Hip.extenseurs,'","',...
        Examination.Rforce.Hip.abducteurs,'","',...
        Examination.Rforce.Hip.adducteurs,'","',...
        Examination.Rforce.Hip.rotInt,'","',...
        Examination.Rforce.Hip.rotExt,'","',...
        Examination.Lforce.Hip.flechisseursDD,'","',...                    % FORCE / HIP / LEFT 
        Examination.Lforce.Hip.extenseurs,'","',...
        Examination.Lforce.Hip.abducteurs,'","',...
        Examination.Lforce.Hip.adducteurs,'","',...
        Examination.Lforce.Hip.rotInt,'","',...
        Examination.Lforce.Hip.rotExt,'","',...
        Examination.Rforce.Knee.flechisseurs,'","',...                     % FORCE / KNEE / RIGHT 
        Examination.Rforce.Knee.extenseurs,'","',... 
        Examination.Lforce.Knee.flechisseurs,'","',...                     % FORCE / KNEE / LEFT 
        Examination.Lforce.Knee.extenseurs,'","',... 
        Examination.Rforce.Ankle.tibialisAnt,'","',...                     % FORCE / ANKLE / RIGHT 
        Examination.Rforce.Ankle.extDigLong,'","',...
        Examination.Rforce.Ankle.extHalLong,'","',...
        Examination.Rforce.Ankle.peroneus,'","',...
        Examination.Rforce.Ankle.tibialisPost,'","',...
        Examination.Rforce.Ankle.gastSol,'","',...
        Examination.Rforce.Ankle.flexDigLong,'","',...
        Examination.Rforce.Ankle.flexHalLong,'","',...
        Examination.Lforce.Ankle.tibialisAnt,'","',...                     % FORCE / ANKLE / LEFT 
        Examination.Lforce.Ankle.extDigLong,'","',...
        Examination.Lforce.Ankle.extHalLong,'","',...
        Examination.Lforce.Ankle.peroneus,'","',...
        Examination.Lforce.Ankle.tibialisPost,'","',...
        Examination.Lforce.Ankle.gastSol,'","',...
        Examination.Lforce.Ankle.flexDigLong,'","',...
        Examination.Lforce.Ankle.flexHalLong,'","',...
        Examination.Rselectivity.Hip.flechisseursDD,'","',...              % SELECTIVITY / HIP / RIGHT 
        Examination.Rselectivity.Hip.extenseurs,'","',...
        Examination.Rselectivity.Hip.abducteurs,'","',...
        Examination.Rselectivity.Hip.adducteurs,'","',...
        Examination.Rselectivity.Hip.rotInt,'","',...
        Examination.Rselectivity.Hip.rotExt,'","',...
        Examination.Lselectivity.Hip.flechisseursDD,'","',...              % SELECTIVITY / HIP / LEFT 
        Examination.Lselectivity.Hip.extenseurs,'","',...
        Examination.Lselectivity.Hip.abducteurs,'","',...
        Examination.Lselectivity.Hip.adducteurs,'","',...
        Examination.Lselectivity.Hip.rotInt,'","',...
        Examination.Lselectivity.Hip.rotExt,'","',...
        Examination.Rselectivity.Knee.flechisseurs,'","',...               % SELECTIVITY / KNEE / RIGHT 
        Examination.Rselectivity.Knee.extenseurs,'","',...
        Examination.Lselectivity.Knee.flechisseurs,'","',...               % SELECTIVITY / KNEE / LEFT 
        Examination.Lselectivity.Knee.extenseurs,'","',...
        Examination.Rselectivity.Ankle.boyd,'","',...                      % SELECTIVITY / ANKLE / RIGHT 
        Examination.Rselectivity.Ankle.confusionTest,'","',...  
        Examination.Rselectivity.Ankle.peroneus,'","',...  
        Examination.Rselectivity.Ankle.tibialisPost,'","',...  
        Examination.Rselectivity.Ankle.gastSol,'","',...  
        Examination.Rselectivity.Ankle.flexDigLong,'","',...  
        Examination.Rselectivity.Ankle.flexHalLong,'","',...  
        Examination.Lselectivity.Ankle.boyd,'","',...                      % SELECTIVITY / ANKLE / LEFT 
        Examination.Lselectivity.Ankle.confusionTest,'","',...  
        Examination.Lselectivity.Ankle.peroneus,'","',...  
        Examination.Lselectivity.Ankle.tibialisPost,'","',...  
        Examination.Lselectivity.Ankle.gastSol,'","',...  
        Examination.Lselectivity.Ankle.flexDigLong,'","',...  
        Examination.Lselectivity.Ankle.flexHalLong,'","',... 
        Examination.Rspasticity.Ashworth.Hip.flechisseursDD,'","',...      % SPASTICITY / ASHWORTH / HIP / RIGHT 
        Examination.Rspasticity.Ashworth.Hip.duncanElyTest,'","',... 
        Examination.Rspasticity.Ashworth.Hip.extenseurs,'","',... 
        Examination.Rspasticity.Ashworth.Hip.abducteurs,'","',... 
        Examination.Rspasticity.Ashworth.Hip.adducteurs,'","',... 
        Examination.Rspasticity.Ashworth.Hip.rotInt,'","',... 
        Examination.Rspasticity.Ashworth.Hip.rotExt,'","',...  
        Examination.Lspasticity.Ashworth.Hip.flechisseursDD,'","',...      % SPASTICITY / ASHWORTH / HIP / LEFT 
        Examination.Lspasticity.Ashworth.Hip.duncanElyTest,'","',... 
        Examination.Lspasticity.Ashworth.Hip.extenseurs,'","',... 
        Examination.Lspasticity.Ashworth.Hip.abducteurs,'","',... 
        Examination.Lspasticity.Ashworth.Hip.adducteurs,'","',... 
        Examination.Lspasticity.Ashworth.Hip.rotInt,'","',... 
        Examination.Lspasticity.Ashworth.Hip.rotExt,'","',...  
        Examination.Rspasticity.Ashworth.Knee.flechisseurs,'","',...       % SPASTICITY / ASHWORTH / KNEE / RIGHT 
        Examination.Rspasticity.Ashworth.Knee.extenseurs,'","',... 
        Examination.Lspasticity.Ashworth.Knee.flechisseurs,'","',...       % SPASTICITY / ASHWORTH / KNEE / LEFT 
        Examination.Lspasticity.Ashworth.Knee.extenseurs,'","',... 
        Examination.Rspasticity.Ashworth.Ankle.tibialisAnt,'","',...       % SPASTICITY / ASHWORTH / ANKLE / RIGHT 
        Examination.Rspasticity.Ashworth.Ankle.extDigLong,'","',... 
        Examination.Rspasticity.Ashworth.Ankle.extHalLong,'","',... 
        Examination.Rspasticity.Ashworth.Ankle.peroneus,'","',... 
        Examination.Rspasticity.Ashworth.Ankle.tibialisPost,'","',... 
        Examination.Rspasticity.Ashworth.Ankle.gastSol,'","',... 
        Examination.Rspasticity.Ashworth.Ankle.flechisseurs,'","',... 
        Examination.Lspasticity.Ashworth.Ankle.tibialisAnt,'","',...       % SPASTICITY / ASHWORTH / ANKLE / LEFT 
        Examination.Lspasticity.Ashworth.Ankle.extDigLong,'","',... 
        Examination.Lspasticity.Ashworth.Ankle.extHalLong,'","',... 
        Examination.Lspasticity.Ashworth.Ankle.peroneus,'","',... 
        Examination.Lspasticity.Ashworth.Ankle.tibialisPost,'","',... 
        Examination.Lspasticity.Ashworth.Ankle.gastSol,'","',... 
        Examination.Lspasticity.Ashworth.Ankle.flechisseurs,'","',... 
        Examination.Rspasticity.Tardieu.Hip.flechisseursDD,'","',...       % SPASTICITY / TARDIEU / HIP / RIGHT 
        Examination.Rspasticity.Tardieu.Hip.duncanElyTest,'","',... 
        Examination.Rspasticity.Tardieu.Hip.extenseurs,'","',... 
        Examination.Rspasticity.Tardieu.Hip.abducteurs,'","',... 
        Examination.Rspasticity.Tardieu.Hip.adducteurs,'","',... 
        Examination.Rspasticity.Tardieu.Hip.rotInt,'","',... 
        Examination.Rspasticity.Tardieu.Hip.rotExt,'","',...  
        Examination.Lspasticity.Tardieu.Hip.flechisseursDD,'","',...       % SPASTICITY / TARDIEU / HIP / LEFT 
        Examination.Lspasticity.Tardieu.Hip.duncanElyTest,'","',... 
        Examination.Lspasticity.Tardieu.Hip.extenseurs,'","',... 
        Examination.Lspasticity.Tardieu.Hip.abducteurs,'","',... 
        Examination.Lspasticity.Tardieu.Hip.adducteurs,'","',... 
        Examination.Lspasticity.Tardieu.Hip.rotInt,'","',... 
        Examination.Lspasticity.Tardieu.Hip.rotExt,'","',...  
        Examination.Rspasticity.Tardieu.Knee.flechisseurs,'","',...        % SPASTICITY / TARDIEU / KNEE / RIGHT 
        Examination.Rspasticity.Tardieu.Knee.extenseurs,'","',... 
        Examination.Lspasticity.Tardieu.Knee.flechisseurs,'","',...        % SPASTICITY / TARDIEU / KNEE / LEFT 
        Examination.Lspasticity.Tardieu.Knee.extenseurs,'","',... 
        Examination.Rspasticity.Tardieu.Ankle.tibialisAnt,'","',...        % SPASTICITY / TARDIEU / ANKLE / RIGHT 
        Examination.Rspasticity.Tardieu.Ankle.extDigLong,'","',... 
        Examination.Rspasticity.Tardieu.Ankle.extHalLong,'","',... 
        Examination.Rspasticity.Tardieu.Ankle.peroneus,'","',... 
        Examination.Rspasticity.Tardieu.Ankle.tibialisPost,'","',... 
        Examination.Rspasticity.Tardieu.Ankle.gastSol,'","',... 
        Examination.Rspasticity.Tardieu.Ankle.R1R2,'","',... 
        Examination.Rspasticity.Tardieu.Ankle.flechisseurs,'","',... 
        Examination.Lspasticity.Tardieu.Ankle.tibialisAnt,'","',...        % SPASTICITY / TARDIEU / ANKLE / LEFT 
        Examination.Lspasticity.Tardieu.Ankle.extDigLong,'","',... 
        Examination.Lspasticity.Tardieu.Ankle.extHalLong,'","',... 
        Examination.Lspasticity.Tardieu.Ankle.peroneus,'","',... 
        Examination.Lspasticity.Tardieu.Ankle.tibialisPost,'","',... 
        Examination.Lspasticity.Tardieu.Ankle.gastSol,'","',... 
        Examination.Lspasticity.Tardieu.Ankle.R1R2,'","',... 
        Examination.Lspasticity.Tardieu.Ankle.flechisseurs,'","',... 
        Examination.Rsensitivity.superficielle,'","',...                   % SENSITIVITY / RIGHT 
        Examination.Rsensitivity.proprioceptive,'","',...        
        Examination.Lsensitivity.superficielle,'","',...                   % SENSITIVITY / LEFT 
        Examination.Lsensitivity.proprioceptive,'","',...    
        Examination.scoliose,'","',...                                     % SCOLIOSE 
        Examination.axeOccipital,'","',...                                 % OCCIPITAL AXIS DEVIATION 
        Examination.rightLegLength,'","',...                               % SENSITIVITY / RIGHT 
        Examination.leftLegLength,'","',...                                % SENSITIVITY / LEFT 
        Examination.group,'")');                                           % GROUP
    db.prepareStatement(merge);
    db.query();
end